package com.pvp.leaderboard.game;

import net.runelite.api.gameval.*;

import static net.runelite.api.gameval.InterfaceID.PvpArenaUnrankedduel.*;
import static net.runelite.api.gameval.VarbitID.*;

public final class ArenaWidgets
{

    public static final int[] SLOT_INDEX = {0, 1, 2, 3, 4, 5, 7, 9, 10, 12, 13};
    public static final String[] SLOT_NAMES = "head cape neck weapon body shield legs hands feet ring ammo".split(" ");
    public static final int BLANK_ID = ItemID.BLANKOBJECT;

    public static final int DUEL_GROUP = InterfaceID.PVP_ARENA_UNRANKEDDUEL;
    public static final int BANK_GROUP = InterfaceID.BANKMAIN;

    public static final int DUEL_ROOT = UNIVERSE;
    public static final int[] DUEL_CONFIRMS = {BUILD_CONFIRM, OPPONENT_CONFIRM};

    public static final int SUPPLIES_ROOT = InterfaceID.PvpArenaStagingareaSupplies.UNIVERSE;

    /** Each build's rune pouch varp. */
    public static final int[] POUCH_VARPS = {VarPlayerID.PVPA_LOADOUT_A_RUNEPOUCH, VarPlayerID.PVPA_LOADOUT_B_RUNEPOUCH,
        VarPlayerID.PVPA_LOADOUT_C_RUNEPOUCH};

    /** One kit panel's component ids: its 11 worn slots, then equipment, inventory, spellbook container / menu /
     *  display, items list, items scrollbar, seek. */
    public static final class KitPanel
    {
        public final int equipment, inventory, bookBox, bookMenu, bookDisplay, itemsList, itemsScroll, seek;
        public final int[] slots;

        KitPanel(int[] slots, int... c)
        {
            this.slots = slots;
            equipment = c[0];
            inventory = c[1];
            bookBox = c[2];
            bookMenu = c[3];
            bookDisplay = c[4];
            itemsList = c[5];
            itemsScroll = c[6];
            seek = c[7];
        }
    }

    public static final KitPanel[] DUEL_PANELS = {
        new KitPanel(new int[]{_0SLOT0, _0SLOT1, _0SLOT2, _0SLOT3, _0SLOT4, _0SLOT5, _0SLOT7, _0SLOT9, _0SLOT10, _0SLOT12, _0SLOT13},
            _0EQUIPMENT, _0INVENTORY, _0SPELLBOOK_CONTAINER, _0SPELLBOOK_MENU, _0SPELLBOOK_DISPLAY, _0ITEMS_LIST, _0ITEMS_SCROLLBAR, _0SEEK),
        new KitPanel(new int[]{_1SLOT0, _1SLOT1, _1SLOT2, _1SLOT3, _1SLOT4, _1SLOT5, _1SLOT7, _1SLOT9, _1SLOT10, _1SLOT12, _1SLOT13},
            _1EQUIPMENT, _1INVENTORY, _1SPELLBOOK_CONTAINER, _1SPELLBOOK_MENU, _1SPELLBOOK_DISPLAY, _1ITEMS_LIST, _1ITEMS_SCROLLBAR, _1SEEK),
        new KitPanel(new int[]{_2SLOT0, _2SLOT1, _2SLOT2, _2SLOT3, _2SLOT4, _2SLOT5, _2SLOT7, _2SLOT9, _2SLOT10, _2SLOT12, _2SLOT13},
            _2EQUIPMENT, _2INVENTORY, _2SPELLBOOK_CONTAINER, _2SPELLBOOK_MENU, _2SPELLBOOK_DISPLAY, _2ITEMS_LIST, _2ITEMS_SCROLLBAR, _2SEEK),
    };
    public static final KitPanel[] SUPPLIES_PANELS = SuppliesPanels.PANELS;

    /** Per build: the 28 inventory and 11 worn loadout varbits in order, then the spellbook varbit at [39]. */
    public static final int[][] LOADOUT_VARBITS = {
        {PVPA_LOADOUT_A_INV_00, PVPA_LOADOUT_A_INV_01, PVPA_LOADOUT_A_INV_02, PVPA_LOADOUT_A_INV_03, PVPA_LOADOUT_A_INV_04,
            PVPA_LOADOUT_A_INV_05, PVPA_LOADOUT_A_INV_06, PVPA_LOADOUT_A_INV_07, PVPA_LOADOUT_A_INV_08, PVPA_LOADOUT_A_INV_09,
            PVPA_LOADOUT_A_INV_10, PVPA_LOADOUT_A_INV_11, PVPA_LOADOUT_A_INV_12, PVPA_LOADOUT_A_INV_13, PVPA_LOADOUT_A_INV_14,
            PVPA_LOADOUT_A_INV_15, PVPA_LOADOUT_A_INV_16, PVPA_LOADOUT_A_INV_17, PVPA_LOADOUT_A_INV_18, PVPA_LOADOUT_A_INV_19,
            PVPA_LOADOUT_A_INV_20, PVPA_LOADOUT_A_INV_21, PVPA_LOADOUT_A_INV_22, PVPA_LOADOUT_A_INV_23, PVPA_LOADOUT_A_INV_24,
            PVPA_LOADOUT_A_INV_25, PVPA_LOADOUT_A_INV_26, PVPA_LOADOUT_A_INV_27, PVPA_LOADOUT_A_WORN_HAT, PVPA_LOADOUT_A_WORN_BACK,
            PVPA_LOADOUT_A_WORN_FRONT, PVPA_LOADOUT_A_WORN_RHAND, PVPA_LOADOUT_A_WORN_TORSO, PVPA_LOADOUT_A_WORN_LHAND, PVPA_LOADOUT_A_WORN_LEGS,
            PVPA_LOADOUT_A_WORN_HANDS, PVPA_LOADOUT_A_WORN_FEET, PVPA_LOADOUT_A_WORN_RING, PVPA_LOADOUT_A_WORN_QUIVER, PVPA_LOADOUT_A_SPELLBOOK},
        {PVPA_LOADOUT_B_INV_00, PVPA_LOADOUT_B_INV_01, PVPA_LOADOUT_B_INV_02, PVPA_LOADOUT_B_INV_03, PVPA_LOADOUT_B_INV_04,
            PVPA_LOADOUT_B_INV_05, PVPA_LOADOUT_B_INV_06, PVPA_LOADOUT_B_INV_07, PVPA_LOADOUT_B_INV_08, PVPA_LOADOUT_B_INV_09,
            PVPA_LOADOUT_B_INV_10, PVPA_LOADOUT_B_INV_11, PVPA_LOADOUT_B_INV_12, PVPA_LOADOUT_B_INV_13, PVPA_LOADOUT_B_INV_14,
            PVPA_LOADOUT_B_INV_15, PVPA_LOADOUT_B_INV_16, PVPA_LOADOUT_B_INV_17, PVPA_LOADOUT_B_INV_18, PVPA_LOADOUT_B_INV_19,
            PVPA_LOADOUT_B_INV_20, PVPA_LOADOUT_B_INV_21, PVPA_LOADOUT_B_INV_22, PVPA_LOADOUT_B_INV_23, PVPA_LOADOUT_B_INV_24,
            PVPA_LOADOUT_B_INV_25, PVPA_LOADOUT_B_INV_26, PVPA_LOADOUT_B_INV_27, PVPA_LOADOUT_B_WORN_HAT, PVPA_LOADOUT_B_WORN_BACK,
            PVPA_LOADOUT_B_WORN_FRONT, PVPA_LOADOUT_B_WORN_RHAND, PVPA_LOADOUT_B_WORN_TORSO, PVPA_LOADOUT_B_WORN_LHAND, PVPA_LOADOUT_B_WORN_LEGS,
            PVPA_LOADOUT_B_WORN_HANDS, PVPA_LOADOUT_B_WORN_FEET, PVPA_LOADOUT_B_WORN_RING, PVPA_LOADOUT_B_WORN_QUIVER, PVPA_LOADOUT_B_SPELLBOOK},
        {PVPA_LOADOUT_C_INV_00, PVPA_LOADOUT_C_INV_01, PVPA_LOADOUT_C_INV_02, PVPA_LOADOUT_C_INV_03, PVPA_LOADOUT_C_INV_04,
            PVPA_LOADOUT_C_INV_05, PVPA_LOADOUT_C_INV_06, PVPA_LOADOUT_C_INV_07, PVPA_LOADOUT_C_INV_08, PVPA_LOADOUT_C_INV_09,
            PVPA_LOADOUT_C_INV_10, PVPA_LOADOUT_C_INV_11, PVPA_LOADOUT_C_INV_12, PVPA_LOADOUT_C_INV_13, PVPA_LOADOUT_C_INV_14,
            PVPA_LOADOUT_C_INV_15, PVPA_LOADOUT_C_INV_16, PVPA_LOADOUT_C_INV_17, PVPA_LOADOUT_C_INV_18, PVPA_LOADOUT_C_INV_19,
            PVPA_LOADOUT_C_INV_20, PVPA_LOADOUT_C_INV_21, PVPA_LOADOUT_C_INV_22, PVPA_LOADOUT_C_INV_23, PVPA_LOADOUT_C_INV_24,
            PVPA_LOADOUT_C_INV_25, PVPA_LOADOUT_C_INV_26, PVPA_LOADOUT_C_INV_27, PVPA_LOADOUT_C_WORN_HAT, PVPA_LOADOUT_C_WORN_BACK,
            PVPA_LOADOUT_C_WORN_FRONT, PVPA_LOADOUT_C_WORN_RHAND, PVPA_LOADOUT_C_WORN_TORSO, PVPA_LOADOUT_C_WORN_LHAND, PVPA_LOADOUT_C_WORN_LEGS,
            PVPA_LOADOUT_C_WORN_HANDS, PVPA_LOADOUT_C_WORN_FEET, PVPA_LOADOUT_C_WORN_RING, PVPA_LOADOUT_C_WORN_QUIVER, PVPA_LOADOUT_C_SPELLBOOK}
    };
}
